//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServiceFolderMonitor.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceCheck")]
    public interface IServiceCheck {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheck/SaveCheck", ReplyAction="http://tempuri.org/IServiceCheck/SaveCheckResponse")]
        void SaveCheck(DataModelLibrary.Check check);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheck/SaveCheck", ReplyAction="http://tempuri.org/IServiceCheck/SaveCheckResponse")]
        System.Threading.Tasks.Task SaveCheckAsync(DataModelLibrary.Check check);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheck/GetLastPack", ReplyAction="http://tempuri.org/IServiceCheck/GetLastPackResponse")]
        System.Collections.Generic.List<DataModelLibrary.Check> GetLastPack(int packSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCheck/GetLastPack", ReplyAction="http://tempuri.org/IServiceCheck/GetLastPackResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Check>> GetLastPackAsync(int packSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCheckChannel : WindowsServiceFolderMonitor.ServiceReference1.IServiceCheck, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCheckClient : System.ServiceModel.ClientBase<WindowsServiceFolderMonitor.ServiceReference1.IServiceCheck>, WindowsServiceFolderMonitor.ServiceReference1.IServiceCheck {
        
        public ServiceCheckClient() {
        }
        
        public ServiceCheckClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCheckClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCheckClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCheckClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveCheck(DataModelLibrary.Check check) {
            base.Channel.SaveCheck(check);
        }
        
        public System.Threading.Tasks.Task SaveCheckAsync(DataModelLibrary.Check check) {
            return base.Channel.SaveCheckAsync(check);
        }
        
        public System.Collections.Generic.List<DataModelLibrary.Check> GetLastPack(int packSize) {
            return base.Channel.GetLastPack(packSize);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Check>> GetLastPackAsync(int packSize) {
            return base.Channel.GetLastPackAsync(packSize);
        }
    }
}
